### ISSUE TITLE
Dell XPS 15 9570 issue

### ISSUE THREAD

**Issue by lastmetroid** [424778940z/bzh-windrv-dell-smm-io#1]
Hey,

I finally tested this on the Dell XP 15 9570, it does not work properly. After disabling EC fan control, I can send manual values to the fans and the EC doesnt seem to "work against it", but then the EC can always still activate the fans for the first kick in.

**Comment by 424778940z** [comment]
EC firmware not always stay the same for all laptops, if it not working properly for your laptop you may want do some research and modify the code, this is an opensource code right?

I put this project public on Github just for save it somewhere, and may benefit for the community, but I have no ability to provide support for all laptops.

**Comment by lastmetroid** [comment]
@424778940z This is low-level hardware programming which is way beyond what I can do :( Is there anything I could help maybe fixing this for the 9570? Provide debug logs or something maybe? I disabled secure boot, enabled test driver mode, started the tool with admin, clicked disable ec, but then I cant control the fans with the tool, sliding the slider left/right it resets always into the middle position. Controlling the fans with HwInfo works, like sending for example 0RPM. But then the Dell EC always overwrites it again sometime later. It seems the driver is doing "something" at least, because the fans dont go off automatically anymore after loading the driver by EC control. They stay on forever until I send another 0RPM via HWInfo to both fans. Then when I trigger a short dGPU poll, they start to spin again.

**Comment by lastmetroid** [comment]
@424778940z The driver doesnt just load it seems. If maybe you could implement a short debug output, why, I am happy to give informations and help make it work on the 9570. I would run a debug version on my laptop if it helps any. I found this debate about 9570 support for smm driver of Linux:
https://patchwork.kernel.org/patch/10701619/
Someone said:

---

Allow the module to be loaded on Dell XPS 9570, without having to use
the "force=1" option. The module loads without problems, and reports
correct fan values

[...]

I've been playing with smm.c from a old version of i8kutils, that
is just an userspace utility to trigger the SMM RPC:

http://sprunge.us/llxG7R

I used that in combination with the following test script:

http://sprunge.us/izJmQK

I managed to run that on a XPS 9560 and 9570 and compare the results.

XPS 9560: http://sprunge.us/xCLNSy
XPS 9570: http://sprunge.us/wSFTKs

The main difference between 9560 and 9570 is that the calls to get
the type of either fan or temperature sensor are not working (they all 
return 0xfff in the eax register), where in the 9560 they're returning
proper values.

However, it looks like the call for reading values (fan speed or 
temperatures) are all returning proper values in 9570 as well.

I'm assuming the following:

- API should be the same between 9560 and 9670 (why should Dell change
   it just now, and just for a single feature?);
- in the 9670 the type calls are not implemented correctly;
- the sensor indexes should be correct (because they work when used to
   read the temperature directly)

Could this be a hint?

**Comment by lastmetroid** [comment]
@424778940z  The person from the post/link above actually claims, that the dell-smm-hwmon ( https://github.com/torvalds/linux/blob/master/drivers/hwmon/dell-smm-hwmon.c ) works fine under Linux on the 9570 but only if you start it with force=1, which skips the model check. At which part in your driver is something like that happening? Is it this part maybe:

// did it work ?
if ((sc->cmd == cmd && sc->data == data && sc->stat1 == stat1 && sc->stat2 == stat2) // function not supported
|| ((cmd & 0xffff) == 0xffff)) // or invalid device
status = 0;

? which needs a skip parameter for the 9570 to work? How does this part in your code know it is an "invalid device"?

**Comment by 424778940z** [comment]
> * API should be the same between 9560 and 9670 (why should Dell change
>   it just now, and just for a single feature?);

API availability may vary  on different hardware. the EC chip may even not the same for the same model, or sometime not even from same brand. 

They have to implement the same API in different chip firmware which is difficult to do, so they may just implement what they need.

the original code also include a function for detect hidden calls, if you interested you can try to use  that to probe, but a batter way is just de-compile the EC firmware

**Comment by lastmetroid** [comment]
@424778940z I got your driver working for the 9570, so the 9570 is still compatible. There is though some kind of bug in your gui tool, and also another Windows issue. Your tool creates a driver service and this seems to become broken/blocked and if that is the case, the driver wont load anymore. Removing the service via sc delete and then creating it manually with the same name your tool uses BZHDELLSMMIO, the driver loads fine and then it also works speaking to it. The fan controlling of your tool though does not work, for whatever reason. Still, the driver works for the 9570. Someone made a new command line tool to use your driver and it works great so far: http://forum.notebookreview.com/threads/dellfancmd-%E2%80%93-tool-to-enable-manual-custom-control-of-the-laptop-fans.827106/
However, just until bios version 1.6.0. With the new bios 1.7.0 the ec off control doesnt work, 100% anymore with your driver for the 9570. So **** Dell changed something, maybe on the registered or added a new one, which would have to be found out, if to want to use it >=1.7.0. Problem with 1.7.0 is, that any dGPU activity would trigger the fans even if ec control register is off. It works perfectly until >=1.6.0.

**Comment by 424778940z** [comment]
I don't think my code actually create any service, this may due to the Qt built in functions.

This project is already many years old, and I don't have a Dell laptop anymore, as I said above, the source code here is just for share with people, not for provide a up to date solution, you are welcome to build you own based on this repo, but I have no time and environment to provide support.
