### ISSUE TITLE
Lid control

### ISSUE THREAD

**Issue by Evengard** [424778940z/bzh-windrv-dell-smm-io#2]
Hello!
I have a G5 5587 notebook which is a hybrid Intel/Nvidia notebook, and it have a "nasty" behaviour which disables the Intel videocard on the lid close, also disconnecting the internal monitor as well if there is a second monitor connected to HDMI.

I wonder if this behaviour may be disabled with the use of your driver. Something like "do nothing on lid close" or "only disable monitor, but do not disconnect it" setting somewhere in SMM. Any advice?

**Comment by 424778940z** [comment]
This is a driver for control fans, it has nothing to do with lid

**Comment by Evengard** [comment]
I thought it would work as it may be somewhere in SMM, and this driver allows accessing SMM.

**Comment by 424778940z** [comment]
There is no public document about the SMM, SMM is a blackbox.
The driver here dose allow you talk with SMM but you have to have an idea for what you should say.

**Comment by Evengard** [comment]
I thought as you had the info about the fans you may have information about other parts of the SMM. Thanks anyway.
